### ISSUE TITLE
Set Data type.

### ISSUE THREAD

**Issue by LucioFranco** [cafebazaar/ecto-cassandra#10]
Hi,

I am trying to get the set data type to work. I can successfully set it in the migration but can not seem to get it to work via the schema. The array data type fails with.

`INSERT INTO chat_rooms (creator, participants, room_name, inserted_at, updated_at) VALUES (?, ?, ?, ?, ?) IF NOT EXISTS [1179, [1179, 15], "test room", ~N[2017-08-09 16:34:40.264752], ~N[2017-08-09 16:34:40.264763]]`
`[warn] Elixir.Cassandra.Session.Executor got error: %FunctionClauseError{arity: 1, function: :to_list, module: MapSet}`

This is what I have in my schema for the set field. `field :participants, {:array, :integer}` I am curious if there is something I can do to make sets work via the schema.

Thanks

**Comment by alirajabi** [comment]
Sorry I've taken so long to reply

You can use `list`, `map` like below

```elixir
# /web/models/test.ex
  @primary_key false
  schema "tests" do
    field :id, :string, primary_key: true, autogenerate: false
    field :peer_id, :binary_id, primary_key: true, autogenerate: false
    field :metadata_list, :list, default: []
    field :metadata, :map, default: %{}
    timestamps()
  end
```

```elixir
# /priv/repo/test.exs
defmodule Uz.Repo.Migrations.Test do
  use Ecto.Migration

  def change do
    create table(:tests, primary_key: false) do
      add :id, :uuid, partition_key: true
      add :peer_id, :uuid, clustering_column: true
      add :metadata_list, :blob
      add :metadata, :blob
      timestamps()
    end
  end
end
```
