### ISSUE TITLE
How to use Mysql and Cassandra in same app 

### ISSUE THREAD

**Issue by imerkle** [cafebazaar/ecto-cassandra#4]
I have a Mysql App. using Mariaex adapter. How can i use that with cassandra adapter ?

**Comment by hzamani** [comment]
As any other Ecto adapter you can use another repo along side your main repo:

```elixir
defmodule App.Repo do
  use Ecto.Repo, otp_app: :app
end

defmodule App.Cassandra.Repo do # or any other name
  use Ecto.Repo, otp_app: :app
end

# in config file
config :app, App.Cassandra.Repo,
  adapter: Ecto.Adapters.MySQL
  # ... other configs

config :app, App.Cassandra.Repo,
  adapter: EctoCassandra.Adapter
  # ... other configs
```

**Comment by yordis** [comment]
@dsslimshaddy can we close this? @hzamani I am just touching base because it will affect the repo rate with open issues like this one, IMO
