### ISSUE TITLE
Rollbacks always time out

### ISSUE THREAD

**Issue by vfsoraki** [cafebazaar/ecto-cassandra#9]
Rollbacks always timeout. This happens because Cassandra takes its time dropping tables and keysapces, and rollbacks or drops time out.

The problem happens after the first timeout, you can't run rollback again. Cassandra continued dropping table, but Elixir app thinks it does not and does not update `schema_migrations`. So next time, table does not exist, and rollback fails. Migrations go into an invalid state. You can never rollback past this point, but you may continue migrating forward.

Although the problem is not critical for `ecto.drop`, but it makes migrations invalid.

I searched to find how I can change the timeout value, and found nothing.

So the question is:
> Is there a way (or a hack :) ) to change timeout when running migrations?

**Comment by alirajabi** [comment]
you can add timeout and connect_timeout to your config.

```elixir
config :app, App.Repo,
  connect_timeout: :infinity,
  timeout: :infinity,
```

**Comment by vfsoraki** [comment]
Thanks, it worked.
